"""empty message

Revision ID: 166158e5a340
Revises: 
Create Date: 2020-01-09 12:42:16.199785

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '166158e5a340'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cities', sa.Column('description', sa.String(length=500), nullable=True))
    op.add_column('cities', sa.Column('image', sa.String(length=100), nullable=True))
    op.add_column('pois', sa.Column('image', sa.String(length=100), nullable=True))
    op.add_column('user_ratings', sa.Column('city_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'user_ratings', 'cities', ['city_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_ratings', type_='foreignkey')
    op.drop_column('user_ratings', 'city_id')
    op.drop_column('pois', 'image')
    op.drop_column('cities', 'image')
    op.drop_column('cities', 'description')
    # ### end Alembic commands ###
