"""empty message

Revision ID: 26db9a676175
Revises: 42edb44d15c8
Create Date: 2020-01-03 11:06:21.242269

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '26db9a676175'
down_revision = '42edb44d15c8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cities', sa.Column('description', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cities', 'description')
    # ### end Alembic commands ###
