"""empty message

Revision ID: 345c0281d4d5
Revises: 0673f9d246ac
Create Date: 2019-12-23 18:10:58.406295

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '345c0281d4d5'
down_revision = '0673f9d246ac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pois', sa.Column('name', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pois', 'name')
    # ### end Alembic commands ###
