"""empty message

Revision ID: 42edb44d15c8
Revises: 345c0281d4d5
Create Date: 2019-12-28 10:52:43.685070

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '42edb44d15c8'
down_revision = '345c0281d4d5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_ratings', sa.Column('city_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'user_ratings', 'cities', ['city_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_ratings', type_='foreignkey')
    op.drop_column('user_ratings', 'city_id')
    # ### end Alembic commands ###
