"""empty message

Revision ID: 776137695e94
Revises: 
Create Date: 2019-12-02 16:51:14.368684

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '776137695e94'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('name', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
