"""empty message

Revision ID: 8bd72a769744
Revises: 743d6ef273d1
Create Date: 2020-01-03 13:35:22.704318

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8bd72a769744'
down_revision = '743d6ef273d1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cities', sa.Column('description', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cities', 'description')
    # ### end Alembic commands ###
