"""empty message

Revision ID: 9c0cb5271326
Revises: 8bd72a769744
Create Date: 2020-01-03 13:35:48.366329

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9c0cb5271326'
down_revision = '8bd72a769744'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cities', 'description')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cities', sa.Column('description', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
