"""empty message

Revision ID: b93ec4ecccf0
Revises: e5e8274a903e
Create Date: 2020-01-07 16:08:18.285102

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b93ec4ecccf0'
down_revision = 'e5e8274a903e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pois', sa.Column('image', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pois', 'image')
    # ### end Alembic commands ###
