"""empty message

Revision ID: c83e7b417114
Revises: 9648ef5b99a1
Create Date: 2019-12-23 15:38:46.377866

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c83e7b417114'
down_revision = '9648ef5b99a1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pois',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('city_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=30), nullable=True),
    sa.ForeignKeyConstraint(['city_id'], ['cities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('user_ratings', sa.Column('poi_id', sa.Integer(), nullable=True))
    op.add_column('user_ratings', sa.Column('rating', sa.Float(), nullable=True))
    op.create_foreign_key(None, 'user_ratings', 'pois', ['poi_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_ratings', type_='foreignkey')
    op.drop_column('user_ratings', 'rating')
    op.drop_column('user_ratings', 'poi_id')
    op.drop_table('pois')
    # ### end Alembic commands ###
