"""empty message

Revision ID: ca4e1d345132
Revises: c83e7b417114
Create Date: 2019-12-23 17:42:51.626168

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ca4e1d345132'
down_revision = 'c83e7b417114'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pois', sa.Column('category', sa.String(length=15), nullable=True))
    op.add_column('pois', sa.Column('closing_time', sa.Float(), nullable=True))
    op.add_column('pois', sa.Column('latitude', sa.Float(), nullable=True))
    op.add_column('pois', sa.Column('longitude', sa.Float(), nullable=True))
    op.add_column('pois', sa.Column('opening_time', sa.Float(), nullable=True))
    op.add_column('pois', sa.Column('time_to_spend', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pois', 'time_to_spend')
    op.drop_column('pois', 'opening_time')
    op.drop_column('pois', 'longitude')
    op.drop_column('pois', 'latitude')
    op.drop_column('pois', 'closing_time')
    op.drop_column('pois', 'category')
    # ### end Alembic commands ###
