"""empty message

Revision ID: f1c8cd123cd4
Revises: 6362bc582ac5
Create Date: 2020-04-27 19:55:45.430483

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f1c8cd123cd4'
down_revision = '6362bc582ac5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('wishlist', sa.Column('value', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('wishlist', 'value')
    # ### end Alembic commands ###
